[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.1"
  DATABASE_URL = "postgresql://neondb_owner:npg_zlOV1GRL8hFq@ep-bold-frost-aixhqxlp-pooler.c-4.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
  ADMIN_JWT_SECRET = "change-this-secret"
  DEFAULT_ADMIN_EMAIL = "admin@nabrel.com"
  DEFAULT_ADMIN_PASSWORD = "ChangeMe123!"

[[plugins]]
  package = "@netlify/plugin-nextjs"
